import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { AuditLogQuerySchema, AuditLogResponseSchema, AuthRequestHeadersSchema, DailyReportQuerySchema, DailyReportResponseSchema, ErrorResponseSchema, PaymentHistoryQuerySchema, PaymentHistoryResponseSchema, type AuditLogQuery, type DailyReportQuery, type PaymentHistoryQuery } from "@cafe/contracts";
import { hashPassword } from "../../auth/password.js";
import { ApplicationError, ErrorCodes } from "../../errors/application-error.js";
import { zodToJsonSchema } from "../../contracts/openapi.js";
import { requireManagerRoute } from "../auth/authorization.js";
import { listPaymentHistory } from "./payment-history.service.js";
import { dailyAccountingReport } from "./daily-report.service.js";
import { listAuditLog } from "./audit-log.service.js";

const category = z.object({ name: z.string().trim().min(1).max(120), displayOrder: z.number().int().min(0), isActive: z.boolean().optional() }).strict();
const product = z.object({ categoryId: z.uuid(), name: z.string().trim().min(1).max(120), priceAmount: z.number().int().nonnegative(), preparationDeadlineMinutes: z.number().int().positive(), displayOrder: z.number().int().min(0), isActive: z.boolean().optional(), isAvailable: z.boolean().optional(), optionGroupIds: z.array(z.uuid()).max(30).optional() }).strict();
const optionGroup = z.object({ name: z.string().trim().min(1).max(120), isActive: z.boolean().optional() }).strict();
const option = z.object({ name: z.string().trim().min(1).max(120), priceAmount: z.number().int().nonnegative(), displayOrder: z.number().int().min(0), isActive: z.boolean().optional(), isAvailable: z.boolean().optional() }).strict();
const table = z.object({ name: z.string().trim().min(1).max(120), seatingLimitMinutes: z.number().int().positive(), displayOrder: z.number().int().min(0), isActive: z.boolean().optional(), waiterCallEnabled: z.boolean().optional() }).strict();
const staff = z.object({ username: z.string().regex(/^[a-z0-9._-]{3,64}$/), password: z.string().min(12).max(128) }).strict();
const staffUpdate = staff.partial().refine((x) => x.username !== undefined || x.password !== undefined);
const settings = z.object({ defaultTableSeatingLimitMinutes: z.number().int().positive() }).strict();

function parsed<T>(schema: z.ZodType<T>, value: unknown): T { const result = schema.safeParse(value); if (!result.success) throw new ApplicationError(400, ErrorCodes.VALIDATION_ERROR, "One or more fields are invalid."); return result.data; }
function defined<T extends Record<string, unknown>>(value: T) { return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined)); }
function entityId(params: unknown): string { const values = Object.values(params as Record<string, unknown>); const value = values[0]; return z.uuid().parse(value); }
async function audit(app: Parameters<FastifyPluginAsync>[0], request: any, operation: string, entityType: string, entityId: string, afterSnapshot: unknown) { await app.prisma.auditLog.create({ data: { actorId: request.authenticatedUser.id, requestId: request.id, operation, entityType, entityId, afterSnapshot: afterSnapshot as any } }); }

export const adminRoutes: FastifyPluginAsync = async (app) => {
  const manager = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"] } };
  const headers = zodToJsonSchema(AuthRequestHeadersSchema);
  const errors = { 400: zodToJsonSchema(ErrorResponseSchema), 401: zodToJsonSchema(ErrorResponseSchema), 403: zodToJsonSchema(ErrorResponseSchema) };
  const list = (model: "category" | "product" | "optionGroup" | "cafeTable" | "user") => async () => ({ data: await (app.prisma[model] as any).findMany({ orderBy: model === "user" ? { username: "asc" } : { displayOrder: "asc" }, ...(model === "user" ? { select: { id: true, username: true, role: true, isActive: true, createdAt: true, updatedAt: true } } : {}) }) });
  app.get("/admin/categories", manager, list("category"));
  app.post("/admin/categories", manager, async (request: any) => { const data = parsed(category, request.body); const row = await app.prisma.category.create({ data: defined(data) as any }); await audit(app, request, "CREATE_CATEGORY", "CATEGORY", row.id, row); return { data: row }; });
  app.patch("/admin/categories/:categoryId", manager, async (request: any) => { const row = await app.prisma.category.update({ where: { id: entityId(request.params) }, data: defined(parsed(category.partial(), request.body)) as any }); await audit(app, request, "UPDATE_CATEGORY", "CATEGORY", row.id, row); return { data: row }; });
  app.post("/admin/categories/:categoryId/archive", manager, async (request: any) => { const row = await app.prisma.category.update({ where: { id: entityId(request.params) }, data: { isActive: false, archivedAt: new Date() } }); await audit(app, request, "ARCHIVE_CATEGORY", "CATEGORY", row.id, row); return { data: row }; });
  app.get("/admin/products", manager, list("product"));
  app.post("/admin/products", manager, async (request: any) => { const data = parsed(product, request.body); const row = await app.prisma.product.create({ data: { ...data, optionGroupIds: undefined, productOptionGroups: data.optionGroupIds ? { create: data.optionGroupIds.map((optionGroupId, displayOrder) => ({ optionGroupId, displayOrder })) } : undefined } as any }); await audit(app, request, "CREATE_PRODUCT", "PRODUCT", row.id, row); return { data: row }; });
  app.patch("/admin/products/:productId", manager, async (request: any) => { const data = parsed(product.partial(), request.body); const row = await app.prisma.product.update({ where: { id: entityId(request.params) }, data: { ...defined({ ...data, optionGroupIds: undefined }), ...(data.optionGroupIds ? { productOptionGroups: { deleteMany: {}, create: data.optionGroupIds.map((optionGroupId, displayOrder) => ({ optionGroupId, displayOrder })) } } : {}) } as any }); await audit(app, request, "UPDATE_PRODUCT", "PRODUCT", row.id, row); return { data: row }; });
  app.post("/admin/products/:productId/archive", manager, async (request: any) => { const row = await app.prisma.product.update({ where: { id: entityId(request.params) }, data: { isActive: false, isAvailable: false, archivedAt: new Date() } }); await audit(app, request, "ARCHIVE_PRODUCT", "PRODUCT", row.id, row); return { data: row }; });
  app.get("/admin/option-groups", manager, list("optionGroup"));
  app.post("/admin/option-groups", manager, async (request: any) => { const row = await app.prisma.optionGroup.create({ data: defined(parsed(optionGroup, request.body)) as any }); await audit(app, request, "CREATE_OPTION_GROUP", "OPTION_GROUP", row.id, row); return { data: row }; });
  app.patch("/admin/option-groups/:optionGroupId", manager, async (request: any) => { const row = await app.prisma.optionGroup.update({ where: { id: entityId(request.params) }, data: defined(parsed(optionGroup.partial(), request.body)) as any }); await audit(app, request, "UPDATE_OPTION_GROUP", "OPTION_GROUP", row.id, row); return { data: row }; });
  app.post("/admin/option-groups/:optionGroupId/options", manager, async (request: any) => { const row = await app.prisma.option.create({ data: { ...defined(parsed(option, request.body)), optionGroupId: entityId(request.params) } as any }); await audit(app, request, "CREATE_OPTION", "OPTION", row.id, row); return { data: row }; });
  app.patch("/admin/option-groups/:optionGroupId/options/:optionId", manager, async (request: any) => { const group = z.object({ optionGroupId: z.uuid() }).parse(request.params).optionGroupId; const optionId = z.object({ optionId: z.uuid() }).parse(request.params).optionId; const row = await app.prisma.option.update({ where: { id: optionId, optionGroupId: group }, data: defined(parsed(option.partial(), request.body)) as any }); await audit(app, request, "UPDATE_OPTION", "OPTION", row.id, row); return { data: row }; });
  app.post("/admin/option-groups/:optionGroupId/options/:optionId/archive", manager, async (request: any) => { const group = z.object({ optionGroupId: z.uuid() }).parse(request.params).optionGroupId; const optionId = z.object({ optionId: z.uuid() }).parse(request.params).optionId; const row = await app.prisma.option.update({ where: { id: optionId, optionGroupId: group }, data: { isActive: false, isAvailable: false, archivedAt: new Date() } }); await audit(app, request, "ARCHIVE_OPTION", "OPTION", row.id, row); return { data: row }; });
  app.get("/admin/tables", manager, list("cafeTable"));
  app.post("/admin/tables", manager, async (request: any) => { const row = await app.prisma.cafeTable.create({ data: defined(parsed(table, request.body)) as any }); await audit(app, request, "CREATE_TABLE", "TABLE", row.id, row); return { data: row }; });
  app.patch("/admin/tables/:tableId", manager, async (request: any) => { const row = await app.prisma.cafeTable.update({ where: { id: entityId(request.params) }, data: defined(parsed(table.partial(), request.body)) as any }); await audit(app, request, "UPDATE_TABLE", "TABLE", row.id, row); return { data: row }; });
  app.post("/admin/tables/:tableId/archive", manager, async (request: any) => { const row = await app.prisma.cafeTable.update({ where: { id: entityId(request.params) }, data: { isActive: false, archivedAt: new Date() } }); await audit(app, request, "ARCHIVE_TABLE", "TABLE", row.id, row); return { data: row }; });
  app.get("/admin/users", manager, list("user"));
  app.post("/admin/users", manager, async (request: any) => { const data = parsed(staff, request.body); const row = await app.prisma.user.create({ data: { username: data.username, passwordHash: await hashPassword(data.password), role: "STAFF" }, select: { id: true, username: true, role: true, isActive: true, createdAt: true, updatedAt: true } }); await audit(app, request, "CREATE_STAFF", "USER", row.id, row); return { data: row }; });
  app.patch("/admin/users/:userId", manager, async (request: any) => { const data = parsed(staffUpdate, request.body); const target = await app.prisma.user.findFirst({ where: { id: entityId(request.params), role: "STAFF" } }); if (!target) throw new ApplicationError(404, ErrorCodes.NOT_FOUND, "The requested Staff account was not found."); const row = await app.prisma.user.update({ where: { id: target.id }, data: { ...(data.username ? { username: data.username } : {}), ...(data.password ? { passwordHash: await hashPassword(data.password) } : {}) }, select: { id: true, username: true, role: true, isActive: true, createdAt: true, updatedAt: true } }); await audit(app, request, "UPDATE_STAFF", "USER", row.id, row); return { data: row }; });
  app.post("/admin/users/:userId/deactivate", manager, async (request: any) => { const target = await app.prisma.user.findFirst({ where: { id: entityId(request.params), role: "STAFF" } }); if (!target) throw new ApplicationError(404, ErrorCodes.NOT_FOUND, "The requested Staff account was not found."); const row = await app.prisma.$transaction(async (tx) => { const updated = await tx.user.update({ where: { id: target.id }, data: { isActive: false } }); await tx.refreshSession.updateMany({ where: { userId: target.id, revokedAt: null }, data: { revokedAt: new Date() } }); return updated; }); await audit(app, request, "DEACTIVATE_STAFF", "USER", row.id, row); return { data: { id: row.id, username: row.username, role: row.role, isActive: row.isActive } }; });
  app.post("/admin/users/:userId/reactivate", manager, async (request: any) => { const target = await app.prisma.user.findFirst({ where: { id: entityId(request.params), role: "STAFF" } }); if (!target) throw new ApplicationError(404, ErrorCodes.NOT_FOUND, "The requested Staff account was not found."); const row = await app.prisma.user.update({ where: { id: target.id }, data: { isActive: true }, select: { id: true, username: true, role: true, isActive: true } }); await audit(app, request, "REACTIVATE_STAFF", "USER", row.id, row); return { data: row }; });
  app.get("/admin/settings", manager, async () => ({ data: await app.prisma.cafeSettings.findFirstOrThrow() }));
  app.patch("/admin/settings", manager, async (request: any) => { const row = await app.prisma.cafeSettings.update({ where: { singletonKey: true }, data: { ...parsed(settings, request.body), updatedById: request.authenticatedUser.id } }); await audit(app, request, "UPDATE_CAFE_SETTINGS", "CAFE_SETTINGS", row.id, row); return { data: row }; });
  app.get<{ Querystring: PaymentHistoryQuery }>("/admin/payments", { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], summary: "List retained payment settlements", headers, querystring: zodToJsonSchema(PaymentHistoryQuerySchema), response: { 200: zodToJsonSchema(PaymentHistoryResponseSchema), ...errors } } }, async (request) => {
    const result = await listPaymentHistory(app.prisma, request.query);
    return { data: { payments: result.payments }, meta: { requestId: request.id, page: result.page } };
  });
  app.get<{ Querystring: DailyReportQuery }>("/admin/reports/daily", { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], summary: "Read the bounded daily accounting report", headers, querystring: zodToJsonSchema(DailyReportQuerySchema), response: { 200: zodToJsonSchema(DailyReportResponseSchema), ...errors } } }, async (request) => {
    const result = await dailyAccountingReport(app.prisma, request.query);
    return { data: result.report, meta: { requestId: request.id, period: request.query.period, range: { from: result.range.from.toISOString(), to: result.range.to.toISOString() } } };
  });
  app.get<{ Querystring: AuditLogQuery }>("/admin/audit-log", { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], summary: "List safe retained audit history", headers, querystring: zodToJsonSchema(AuditLogQuerySchema), response: { 200: zodToJsonSchema(AuditLogResponseSchema), ...errors } } }, async (request) => {
    const result = await listAuditLog(app.prisma, request.query);
    return { data: { entries: result.entries }, meta: { requestId: request.id, page: result.page } };
  });
};
