import type { FastifyPluginAsync } from "fastify";
import { z } from "zod";
import { AdminCategoriesResponseSchema, AdminCategoryInputSchema, AdminCategoryResponseSchema, AdminOptionGroupInputSchema, AdminOptionGroupResponseSchema, AdminOptionGroupsResponseSchema, AdminOptionInputSchema, AdminOptionResponseSchema, AdminProductInputSchema, AdminProductResponseSchema, AdminProductsResponseSchema, AdminSettingsResponseSchema, AdminSettingsUpdateSchema, AdminStaffInputSchema, AdminStaffSingleResponseSchema, AdminStaffResponseSchema, AdminStaffUpdateSchema, AdminTableInputSchema, AdminTableResponseSchema, AdminTablesResponseSchema, AuditLogQuerySchema, AuditLogResponseSchema, AuthRequestHeadersSchema, DailyReportQuerySchema, DailyReportResponseSchema, ErrorResponseSchema, PaymentHistoryQuerySchema, PaymentHistoryResponseSchema, type AuditLogQuery, type DailyReportQuery, type PaymentHistoryQuery } from "@cafe/contracts";
import { hashPassword } from "../../auth/password.js";
import { ApplicationError, ErrorCodes } from "../../errors/application-error.js";
import { zodToJsonSchema } from "../../contracts/openapi.js";
import { requireManagerRoute } from "../auth/authorization.js";
import { listPaymentHistory } from "./payment-history.service.js";
import { dailyAccountingReport } from "./daily-report.service.js";
import { listAuditLog } from "./audit-log.service.js";

const category = AdminCategoryInputSchema;
const product = AdminProductInputSchema;
const optionGroup = AdminOptionGroupInputSchema;
const option = AdminOptionInputSchema;
const table = AdminTableInputSchema;
const staff = AdminStaffInputSchema;
const staffUpdate = AdminStaffUpdateSchema;
const settings = AdminSettingsUpdateSchema;

function parsed<T>(schema: z.ZodType<T>, value: unknown): T { const result = schema.safeParse(value); if (!result.success) throw new ApplicationError(400, ErrorCodes.VALIDATION_ERROR, "One or more fields are invalid."); return result.data; }
function defined<T extends Record<string, unknown>>(value: T) { return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined)); }
function entityId(params: unknown): string { return z.uuid().parse(Object.values(params as Record<string, unknown>)[0]); }
function meta(request: { id: string }) { return { requestId: request.id }; }
function asCategory(row: any) { return { id: row.id, name: row.name, displayOrder: row.displayOrder, isActive: row.isActive, archivedAt: row.archivedAt?.toISOString() ?? null }; }
function asProduct(row: any) { return { id: row.id, categoryId: row.categoryId, name: row.name, priceAmount: row.priceAmount, preparationDeadlineMinutes: row.preparationDeadlineMinutes, displayOrder: row.displayOrder, isActive: row.isActive, isAvailable: row.isAvailable, archivedAt: row.archivedAt?.toISOString() ?? null, image: row.image ? { storageKey: row.image.storageKey, altText: row.image.altText } : null, optionGroups: row.productOptionGroups.map((entry: any) => ({ optionGroupId: entry.optionGroupId, displayOrder: entry.displayOrder, minSelections: entry.minSelections, maxSelections: entry.maxSelections, options: entry.allowedOptions.map((option: any) => ({ optionId: option.optionId, displayOrder: option.displayOrder, priceAmountOverride: option.priceAmountOverride })) })) }; }
function asOption(row: any) { return { id: row.id, name: row.name, priceAmount: row.priceAmount, displayOrder: row.displayOrder, isActive: row.isActive, isAvailable: row.isAvailable, archivedAt: row.archivedAt?.toISOString() ?? null }; }
function asOptionGroup(row: any) { return { id: row.id, name: row.name, isActive: row.isActive, options: row.options.map(asOption) }; }
function asTable(row: any) { return { id: row.id, name: row.name, displayOrder: row.displayOrder, isActive: row.isActive, waiterCallEnabled: row.waiterCallEnabled, archivedAt: row.archivedAt?.toISOString() ?? null }; }
function asStaff(row: any) { return { id: row.id, username: row.username, role: "STAFF" as const, isActive: row.isActive, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }; }

export const adminRoutes: FastifyPluginAsync = async (app) => {
  const headers = zodToJsonSchema(AuthRequestHeadersSchema);
  const errors = { 400: zodToJsonSchema(ErrorResponseSchema), 401: zodToJsonSchema(ErrorResponseSchema), 403: zodToJsonSchema(ErrorResponseSchema), 404: zodToJsonSchema(ErrorResponseSchema) };
  const manager = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, response: errors } };
  const categoryParams = zodToJsonSchema(z.object({ categoryId: z.uuid() }));
  const categoryRead = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, response: { 200: zodToJsonSchema(AdminCategoriesResponseSchema), ...errors } } };
  const categoryWrite = (body: z.ZodTypeAny) => ({ preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, body: zodToJsonSchema(body), response: { 200: zodToJsonSchema(AdminCategoryResponseSchema), ...errors } } });
  const categoryArchive = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, params: categoryParams, response: { 200: zodToJsonSchema(AdminCategoryResponseSchema), ...errors } } };
  const productParams = zodToJsonSchema(z.object({ productId: z.uuid() }));
  const productRead = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, response: { 200: zodToJsonSchema(AdminProductsResponseSchema), ...errors } } };
  const productWrite = (body: z.ZodTypeAny) => ({ preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, params: productParams, body: zodToJsonSchema(body), response: { 200: zodToJsonSchema(AdminProductResponseSchema), ...errors } } });
  const productArchive = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, params: productParams, response: { 200: zodToJsonSchema(AdminProductResponseSchema), ...errors } } };
  const optionGroupParams = zodToJsonSchema(z.object({ optionGroupId: z.uuid() }));
  const optionParams = zodToJsonSchema(z.object({ optionGroupId: z.uuid(), optionId: z.uuid() }));
  const optionGroupRead = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, response: { 200: zodToJsonSchema(AdminOptionGroupsResponseSchema), ...errors } } };
  const optionGroupWrite = (body: z.ZodTypeAny, params?: unknown) => ({ preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, ...(params ? { params } : {}), body: zodToJsonSchema(body), response: { 200: zodToJsonSchema(AdminOptionGroupResponseSchema), ...errors } } });
  const optionWrite = (body: z.ZodTypeAny, params = optionParams) => ({ preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, params, body: zodToJsonSchema(body), response: { 200: zodToJsonSchema(AdminOptionResponseSchema), ...errors } } });
  const optionArchive = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, params: optionParams, response: { 200: zodToJsonSchema(AdminOptionResponseSchema), ...errors } } };
  const tableParams = zodToJsonSchema(z.object({ tableId: z.uuid() }));
  const tableRead = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, response: { 200: zodToJsonSchema(AdminTablesResponseSchema), ...errors } } };
  const tableWrite = (body: z.ZodTypeAny, params?: unknown) => ({ preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, ...(params ? { params } : {}), body: zodToJsonSchema(body), response: { 200: zodToJsonSchema(AdminTableResponseSchema), ...errors } } });
  const tableArchive = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, params: tableParams, response: { 200: zodToJsonSchema(AdminTableResponseSchema), ...errors } } };
  const userParams = zodToJsonSchema(z.object({ userId: z.uuid() }));
  const staffRead = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, response: { 200: zodToJsonSchema(AdminStaffResponseSchema), ...errors } } };
  const staffWrite = (body: z.ZodTypeAny, params?: unknown) => ({ preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, ...(params ? { params } : {}), body: zodToJsonSchema(body), response: { 200: zodToJsonSchema(AdminStaffSingleResponseSchema), ...errors } } });
  const staffAction = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, params: userParams, response: { 200: zodToJsonSchema(AdminStaffSingleResponseSchema), ...errors } } };
  const settingsRead = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, response: { 200: zodToJsonSchema(AdminSettingsResponseSchema), ...errors } } };
  const settingsWrite = { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, body: zodToJsonSchema(settings), response: { 200: zodToJsonSchema(AdminSettingsResponseSchema), ...errors } } };
  const productInclude = { image: true, productOptionGroups: { orderBy: { displayOrder: "asc" as const }, include: { allowedOptions: { orderBy: { displayOrder: "asc" as const } } } } };
  const products = () => app.prisma.product.findMany({ where: { isActive: true, archivedAt: null }, orderBy: { displayOrder: "asc" }, include: productInclude });
  const oneProduct = (id: string) => app.prisma.product.findUniqueOrThrow({ where: { id }, include: productInclude });
  const optionGroups = () => app.prisma.optionGroup.findMany({ where: { isActive: true, archivedAt: null }, orderBy: { name: "asc" }, include: { options: { where: { isActive: true, archivedAt: null }, orderBy: { displayOrder: "asc" } } } });
  const oneOptionGroup = (id: string) => app.prisma.optionGroup.findUniqueOrThrow({ where: { id }, include: { options: { orderBy: { displayOrder: "asc" } } } });
  const audit = async (...args: any[]) => {
    const [tx, operation, entityType, entityId, afterSnapshot, request] = typeof args[0] === "string" ? [app.prisma, ...args] : args;
    return tx.auditLog.create({ data: { actorId: request.authenticatedUser.id, requestId: request.id, operation, entityType, entityId, afterSnapshot: afterSnapshot as any } });
  };
  const write = <T>(operation: string, entityType: string, request: any, action: (tx: any) => Promise<T & { id: string }>) => app.prisma.$transaction(async (tx) => { const row = await action(tx); await audit(tx, operation, entityType, row.id, row, request); return row; });

  app.get("/admin/categories", categoryRead, async (request) => ({ data: { categories: (await app.prisma.category.findMany({ where: { isActive: true, archivedAt: null }, orderBy: { displayOrder: "asc" } })).map(asCategory) }, meta: meta(request) }));
  app.post("/admin/categories", categoryWrite(category), async (request: any) => { const row = await write("CREATE_CATEGORY", "CATEGORY", request, (tx) => tx.category.create({ data: defined(parsed(category, request.body)) as any })); return { data: asCategory(row), meta: meta(request) }; });
  app.patch("/admin/categories/:categoryId", categoryWrite(category.partial()), async (request: any) => { const row = await write("UPDATE_CATEGORY", "CATEGORY", request, (tx) => tx.category.update({ where: { id: entityId(request.params) }, data: defined(parsed(category.partial(), request.body) as any) })); return { data: asCategory(row), meta: meta(request) }; });
  app.post("/admin/categories/:categoryId/archive", categoryArchive, async (request: any) => { const row = await write("ARCHIVE_CATEGORY", "CATEGORY", request, (tx) => tx.category.update({ where: { id: entityId(request.params) }, data: { isActive: false, archivedAt: new Date() } })); return { data: asCategory(row), meta: meta(request) }; });
  app.get("/admin/products", productRead, async (request) => ({ data: { products: (await products()).map(asProduct) }, meta: meta(request) }));
  const optionGroupsData = (groups: any[] | undefined) => groups === undefined ? undefined : { create: groups.map((group) => ({ optionGroupId: group.optionGroupId, displayOrder: group.displayOrder, minSelections: group.minSelections, maxSelections: group.maxSelections, allowedOptions: { create: group.options.map((option: any) => ({ optionId: option.optionId, displayOrder: option.displayOrder, priceAmountOverride: option.priceAmountOverride ?? null })) } })) };
  app.post("/admin/products", { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], headers, body: zodToJsonSchema(product), response: { 200: zodToJsonSchema(AdminProductResponseSchema), ...errors } } }, async (request: any) => { const data = parsed(product, request.body); const row = await write("CREATE_PRODUCT", "PRODUCT", request, (tx) => tx.product.create({ data: { ...data, optionGroups: undefined, productOptionGroups: optionGroupsData(data.optionGroups) } as any })); return { data: asProduct(await oneProduct(row.id)), meta: meta(request) }; });
  app.patch("/admin/products/:productId", productWrite(product.partial()), async (request: any) => { const data = parsed(product.partial(), request.body); const productId = entityId(request.params); const row = await write("UPDATE_PRODUCT", "PRODUCT", request, async (tx) => { if (data.optionGroups !== undefined) { await tx.productOptionGroupOption.deleteMany({ where: { productId } }); await tx.productOptionGroup.deleteMany({ where: { productId } }); } return tx.product.update({ where: { id: productId }, data: { ...defined({ ...data, optionGroups: undefined }), ...(data.optionGroups !== undefined ? { productOptionGroups: { create: data.optionGroups.map((group) => ({ optionGroupId: group.optionGroupId, displayOrder: group.displayOrder, minSelections: group.minSelections, maxSelections: group.maxSelections, allowedOptions: { create: group.options.map((option) => ({ optionId: option.optionId, displayOrder: option.displayOrder, priceAmountOverride: option.priceAmountOverride ?? null })) } })) } } : {}) } as any }); }); return { data: asProduct(await oneProduct(row.id)), meta: meta(request) }; });
  app.post("/admin/products/:productId/archive", productArchive, async (request: any) => { const row = await write("ARCHIVE_PRODUCT", "PRODUCT", request, (tx) => tx.product.update({ where: { id: entityId(request.params) }, data: { isActive: false, isAvailable: false, archivedAt: new Date() } })); return { data: asProduct(await oneProduct(row.id)), meta: meta(request) }; });
  app.get("/admin/option-groups", optionGroupRead, async (request) => ({ data: { optionGroups: (await optionGroups()).map(asOptionGroup) }, meta: meta(request) }));
  app.post("/admin/option-groups", optionGroupWrite(optionGroup, undefined), async (request: any) => { const row = await write("CREATE_OPTION_GROUP", "OPTION_GROUP", request, (tx) => tx.optionGroup.create({ data: defined(parsed(optionGroup, request.body)) as any })); return { data: asOptionGroup(await oneOptionGroup(row.id)), meta: meta(request) }; });
  app.patch("/admin/option-groups/:optionGroupId", optionGroupWrite(optionGroup.partial()), async (request: any) => { const row = await write("UPDATE_OPTION_GROUP", "OPTION_GROUP", request, (tx) => tx.optionGroup.update({ where: { id: entityId(request.params) }, data: defined(parsed(optionGroup.partial(), request.body) as any) })); return { data: asOptionGroup(await oneOptionGroup(row.id)), meta: meta(request) }; });
  app.post("/admin/option-groups/:optionGroupId/options", optionWrite(option, optionGroupParams), async (request: any) => { const row = await write("CREATE_OPTION", "OPTION", request, (tx) => tx.option.create({ data: { ...defined(parsed(option, request.body)), optionGroupId: entityId(request.params) } as any })); return { data: asOption(row), meta: meta(request) }; });
  app.patch("/admin/option-groups/:optionGroupId/options/:optionId", optionWrite(option.partial()), async (request: any) => { const params = z.object({ optionGroupId: z.uuid(), optionId: z.uuid() }).parse(request.params); const row = await write("UPDATE_OPTION", "OPTION", request, (tx) => tx.option.update({ where: { id: params.optionId, optionGroupId: params.optionGroupId }, data: defined(parsed(option.partial(), request.body) as any) })); return { data: asOption(row), meta: meta(request) }; });
  app.post("/admin/option-groups/:optionGroupId/options/:optionId/archive", optionArchive, async (request: any) => { const params = z.object({ optionGroupId: z.uuid(), optionId: z.uuid() }).parse(request.params); const row = await write("ARCHIVE_OPTION", "OPTION", request, (tx) => tx.option.update({ where: { id: params.optionId, optionGroupId: params.optionGroupId }, data: { isActive: false, isAvailable: false, archivedAt: new Date() } })); return { data: asOption(row), meta: meta(request) }; });
  app.get("/admin/tables", tableRead, async (request) => ({ data: { tables: (await app.prisma.cafeTable.findMany({ orderBy: { displayOrder: "asc" } })).map(asTable) }, meta: meta(request) }));
  app.post("/admin/tables", tableWrite(table), async (request: any) => { const row = await write("CREATE_TABLE", "TABLE", request, (tx) => tx.cafeTable.create({ data: defined(parsed(table, request.body)) as any })); return { data: asTable(row), meta: meta(request) }; });
  app.patch("/admin/tables/:tableId", tableWrite(table.partial(), tableParams), async (request: any) => { const row = await write("UPDATE_TABLE", "TABLE", request, (tx) => tx.cafeTable.update({ where: { id: entityId(request.params) }, data: defined(parsed(table.partial(), request.body) as any) })); return { data: asTable(row), meta: meta(request) }; });
  app.post("/admin/tables/:tableId/archive", tableArchive, async (request: any) => { const tableId = entityId(request.params); const row = await write("ARCHIVE_TABLE", "TABLE", request, async (tx) => { const current = await tx.cafeTable.findUnique({ where: { id: tableId }, select: { occupancyState: true } }); const openOrder = await tx.order.findFirst({ where: { tableId, state: "OPEN", channel: "TABLE" }, select: { id: true } }); const pendingCall = await tx.waiterCall.findFirst({ where: { tableId, status: "PENDING" }, select: { id: true } }); if (!current || current.occupancyState === "OCCUPIED" || openOrder || pendingCall) throw new ApplicationError(409, ErrorCodes.INVALID_STATE, "An occupied table or a table with active work cannot be archived."); return tx.cafeTable.update({ where: { id: tableId }, data: { isActive: false, archivedAt: new Date() } }); }); return { data: asTable(row), meta: meta(request) }; });
  app.get("/admin/users", staffRead, async (request) => ({ data: { staff: (await app.prisma.user.findMany({ where: { role: "STAFF" }, orderBy: { username: "asc" }, select: { id: true, username: true, isActive: true, createdAt: true, updatedAt: true } })).map(asStaff) }, meta: meta(request) }));
  app.post("/admin/users", staffWrite(staff), async (request: any) => { const data = parsed(staff, request.body); const passwordHash = await hashPassword(data.password); const row = await write("CREATE_STAFF", "USER", request, (tx) => tx.user.create({ data: { username: data.username, passwordHash, role: "STAFF" }, select: { id: true, username: true, isActive: true, createdAt: true, updatedAt: true } })); return { data: asStaff(row), meta: meta(request) }; });
  app.patch("/admin/users/:userId", staffWrite(staffUpdate, userParams), async (request: any) => { const data = parsed(staffUpdate, request.body); const userId = entityId(request.params); const passwordHash = data.password ? await hashPassword(data.password) : undefined; const row = await write("UPDATE_STAFF", "USER", request, async (tx) => { const target = await tx.user.findFirst({ where: { id: userId, role: "STAFF" } }); if (!target) throw new ApplicationError(404, ErrorCodes.NOT_FOUND, "The requested Staff account was not found."); const updated = await tx.user.update({ where: { id: target.id }, data: { ...(data.username ? { username: data.username } : {}), ...(passwordHash ? { passwordHash } : {}) }, select: { id: true, username: true, isActive: true, createdAt: true, updatedAt: true } }); if (passwordHash) await tx.refreshSession.updateMany({ where: { userId: target.id, revokedAt: null }, data: { revokedAt: new Date() } }); return updated; }); return { data: asStaff(row), meta: meta(request) }; });
  app.post("/admin/users/:userId/deactivate", staffAction, async (request: any) => { const userId = entityId(request.params); const row = await write("DEACTIVATE_STAFF", "USER", request, async (tx) => { const target = await tx.user.findFirst({ where: { id: userId, role: "STAFF" } }); if (!target) throw new ApplicationError(404, ErrorCodes.NOT_FOUND, "The requested Staff account was not found."); const updated = await tx.user.update({ where: { id: target.id }, data: { isActive: false }, select: { id: true, username: true, isActive: true, createdAt: true, updatedAt: true } }); await tx.refreshSession.updateMany({ where: { userId: target.id, revokedAt: null }, data: { revokedAt: new Date() } }); return updated; }); return { data: asStaff(row), meta: meta(request) }; });
  app.post("/admin/users/:userId/reactivate", staffAction, async (request: any) => { const userId = entityId(request.params); const row = await write("REACTIVATE_STAFF", "USER", request, async (tx) => { const target = await tx.user.findFirst({ where: { id: userId, role: "STAFF" } }); if (!target) throw new ApplicationError(404, ErrorCodes.NOT_FOUND, "The requested Staff account was not found."); return tx.user.update({ where: { id: target.id }, data: { isActive: true }, select: { id: true, username: true, isActive: true, createdAt: true, updatedAt: true } }); }); return { data: asStaff(row), meta: meta(request) }; });
  app.get("/admin/settings", settingsRead, async (request) => { const row = await app.prisma.cafeSettings.upsert({ where: { singletonKey: true }, create: { tableSeatingLimitMinutes: null }, update: {} }); return { data: { id: row.id, tableSeatingLimitMinutes: row.tableSeatingLimitMinutes, updatedAt: row.updatedAt.toISOString() }, meta: meta(request) }; });
  app.patch("/admin/settings", settingsWrite, async (request: any) => { const data = parsed(settings, request.body); const row: any = await write("UPDATE_CAFE_SETTINGS", "CAFE_SETTINGS", request, (tx) => tx.cafeSettings.upsert({ where: { singletonKey: true }, create: { ...data, updatedById: request.authenticatedUser.id }, update: { ...data, updatedById: request.authenticatedUser.id } })); return { data: { id: row.id, tableSeatingLimitMinutes: row.tableSeatingLimitMinutes, updatedAt: row.updatedAt.toISOString() }, meta: meta(request) }; });
  app.get<{ Querystring: PaymentHistoryQuery }>("/admin/payments", { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], summary: "List retained payment settlements", headers, querystring: zodToJsonSchema(PaymentHistoryQuerySchema), response: { 200: zodToJsonSchema(PaymentHistoryResponseSchema), ...errors } } }, async (request) => { const result = await listPaymentHistory(app.prisma, request.query); return { data: { payments: result.payments }, meta: { requestId: request.id, page: result.page } }; });
  app.get<{ Querystring: DailyReportQuery }>("/admin/reports/daily", { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], summary: "Read the bounded daily accounting report", headers, querystring: zodToJsonSchema(DailyReportQuerySchema), response: { 200: zodToJsonSchema(DailyReportResponseSchema), ...errors } } }, async (request) => { const result = await dailyAccountingReport(app.prisma, request.query); return { data: result.report, meta: { requestId: request.id, period: request.query.period, range: { from: result.range.from.toISOString(), to: result.range.to.toISOString() } } }; });
  app.get<{ Querystring: AuditLogQuery }>("/admin/audit-log", { preHandler: requireManagerRoute, schema: { tags: ["Manager administration"], summary: "List safe retained audit history", headers, querystring: zodToJsonSchema(AuditLogQuerySchema), response: { 200: zodToJsonSchema(AuditLogResponseSchema), ...errors } } }, async (request) => { const result = await listAuditLog(app.prisma, request.query); return { data: { entries: result.entries }, meta: { requestId: request.id, page: result.page } }; });
};
