import { configuredPrinter, printerResolutionIssue, resolvePrinter } from "./printer-resolver";
import { connectedQz, qzDiagnostics } from "./qz-client";
import { thermalDocument } from "./thermal-document";
import { PrintServiceError, type PrinterDiagnostics, type PrinterRole, type PrintKind } from "./types";
const activeJobs = new Map<string, Promise<void>>(); let lastFailure: string | null = null;
const roleFor = (kind: PrintKind): PrinterRole => kind === "bar-ticket" ? "BAR" : "RECEIPT";
function friendlyError(error: unknown): PrintServiceError { if (error instanceof PrintServiceError) return error; const message = error instanceof Error ? error.message : "Unknown QZ failure"; if (/certificate|sign/i.test(message)) return new PrintServiceError("SIGNING", "تنظیمات امن سرویس چاپ کامل نیست."); if (/connect|websocket|qz/i.test(message)) return new PrintServiceError("QZ_UNAVAILABLE", "سرویس چاپ QZ Tray در دسترس نیست. QZ Tray را روی سیستم صندوق اجرا کنید."); return new PrintServiceError("PRINT_REJECTED", "ارسال فیش به چاپگر انجام نشد."); }
export async function printerDiagnostics(): Promise<PrinterDiagnostics> { try { const status = await qzDiagnostics(); return { connected: status.connected, configuredPrinter: configuredPrinter("RECEIPT"), resolvedPrinter: resolvePrinter("RECEIPT", status.printers), printers: status.printers, lastFailure }; } catch (error) { lastFailure = friendlyError(error).message; return { connected: false, configuredPrinter: configuredPrinter("RECEIPT"), resolvedPrinter: null, printers: [], lastFailure }; } }
export function printThermalDocument(orderId: string, kind: PrintKind, settlementId?: string): Promise<void> { const jobKey = `${kind}:${orderId}:${settlementId ?? ""}`; const existing = activeJobs.get(jobKey); if (existing) return existing; const job = (async () => { try { const role = roleFor(kind); const qz = await connectedQz(); const found = await qz.printers.find(); const printers = Array.isArray(found) ? found : [found]; const issue = printerResolutionIssue(role, printers); if (issue === "ambiguous") throw new PrintServiceError("PRINTER_AMBIGUOUS", "چند چاپگر حرارتی پیدا شد؛ چاپگر موردنظر را در تنظیمات صندوق انتخاب کنید."); const printer = resolvePrinter(role, printers); if (!printer) throw new PrintServiceError("PRINTER_NOT_FOUND", "چاپگر حرارتی تنظیم‌شده پیدا نشد."); const html = await thermalDocument(orderId, kind, settlementId); const config = qz.configs.create(printer, { margins: 0, orientation: "portrait", colorType: "blackwhite", scaleContent: false, units: "in", size: { width: 3.15 }, jobName: kind === "bar-ticket" ? "Run Cafe bar ticket" : "Run Cafe receipt" }); await qz.print(config, [{ type: "pixel", format: "html", flavor: "plain", data: html, options: { pageWidth: 3.15 } }]); lastFailure = null; } catch (error) { const failure = friendlyError(error); lastFailure = failure.message; console.error("QZ print submission failed", { code: failure.code, message: error instanceof Error ? error.message : String(error) }); throw failure; } })(); activeJobs.set(jobKey, job); void job.finally(() => activeJobs.delete(jobKey)).catch(() => undefined); return job; }
export const printBarTicket = (orderId: string) => printThermalDocument(orderId, "bar-ticket"); export const printOrderReceipt = (orderId: string) => printThermalDocument(orderId, "receipt"); export const printSettlementReceipt = (orderId: string, settlementId: string) => printThermalDocument(orderId, "settlement", settlementId);
